name: CI Pipeline

# Định nghĩa các sự kiện trigger
on:
  push:
    branches:
      - main  # Chạy workflow khi có thay đổi trên nhánh 'main'
  pull_request:
    branches:
      - main  # Chạy workflow khi có pull request vào nhánh 'main'

# Định nghĩa jobs để thực hiện
jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên máy chủ Ubuntu

    steps:
    # Bước 1: Lấy code về từ repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Bước 2: Cài đặt Node.js (hoặc môi trường khác nếu bạn làm việc với ngôn ngữ khác)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Bước 3: Cài đặt các phụ thuộc của dự án
    - name: Install dependencies
      run: npm install

    # Bước 4: Chạy tests
    - name: Run tests
      run: npm test
